worker_processes  auto;
error_log stderr warn;
pid /run/nginx.pid;

events {
    worker_connections  10240;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main_timed  '$remote_addr - $remote_user [$time_local] "$request" '
                            '$status $body_bytes_sent "$http_referer" '
                            '"$http_user_agent" "$http_x_forwarded_for" '
                            '$request_time $upstream_response_time $pipe $upstream_cache_status';

    log_format  cip         '"$http_x_cip" - "$http_x_forwarded_for" - [$time_local] "$request" $status $bytes_sent "$http_referer" "$http_user_agent" - $host';

    access_log /dev/stdout cip;
    error_log /dev/stderr notice;

    keepalive_timeout  65;

    server {
        listen [::]:8080 default_server;
        listen 8080 default_server;
        server_name _;

        sendfile off;
	client_body_buffer_size 10M;
	client_max_body_size 256M;

        root /web/root;
        index index.php index.html;
	

            # First attempt to serve request as file, then
            # as directory, then fall back to index.php
	location / {
            try_files $uri $uri/ /index.php?q=$uri&$args;
        }

	# enable open CORS for now until we need to adjust
	#location / {
	# if ($http_origin ~* "^https?://[^/]*(vs3|vscdns)\.com$" {
	#    add_header 'Access-Control-Allow-Origin' $http_origin;
	#    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE, PUT';
	#    add_header 'Access-Control-Allow-Credentials' 'true';
	#    add_header 'Access-Control-Allow-Headers' 'User-Agent,Keep-Alive,Content-Type';
	# }
	#}

        # redirect server error pages to the static page /50x.html
        #
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /var/lib/nginx/html;
        }

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass  127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param SCRIPT_NAME $fastcgi_script_name;
            fastcgi_index index.php;
	    fastcgi_buffer_size 256k;
	    fastcgi_buffers 32 256k;
            include fastcgi_params;
        }

        location ~* \.(jpg|jpeg|gif|png|css|js|ico|xml)$ {
            expires 5d;
        }

        # deny access to . files, for security
        #
        location ~ /\. {
            log_not_found off;
            deny all;
        }

        # allow fpm ping and status from localhost
        #
        location ~ ^/(fpm-status|fpm-ping)$ {
            access_log off;
            allow 127.0.0.1;
            allow 10.0.0.0/8;
            deny all;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
        }
    }
}

